import Head from 'next/head';
// import Image from 'next/image';
import { Button } from 'antd';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">SmartRails!</a>
        </h1>

        <p className={styles.description}>
          <code className={styles.code}>
            An Online Railway Reservation System
          </code>
        </p>

        <Button type="primary">Click Me</Button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Designed by Koscee
        </a>
      </footer>
    </div>
  );
}
